workflows:
  nativescript-android:
    name: NativeScript Android Build
    environment:
      vars:
        NODE_VERSION: 18
        JAVA_VERSION: 17
      flutter: stable
      xcode: latest
    scripts:
      - name: Install NVM and Node.js
        script: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"
          nvm install $NODE_VERSION
          nvm use $NODE_VERSION
          node -v  # Verify Node.js version

      - name: Install NativeScript CLI
        script: |
          npm install -g nativescript
      - name: Install Dependencies
        script: |
          npm install
      - name: Build Android Release
        script: |
          export KEYSTORE_PASSWORD=$ANDROID_KEYSTORE_KEYSTORE_PASSWORD
          export KEYSTORE_ALIAS=$ANDROID_KEYSTORE_KEYSTORE_ALIAS
          export KEYSTORE_ALIAS_PASSWORD=$ANDROID_KEYSTORE_KEYSTORE_ALIAS_PASSWORD
          export KEYSTORE_PATH=$ANDROID_KEYSTORE_KEYSTORE_PATH

          tns build android --release \
            --key-store-path $KEYSTORE_PATH \
            --key-store-password $KEYSTORE_PASSWORD \
            --key-store-alias $KEYSTORE_ALIAS \
            --key-store-alias-password $KEYSTORE_ALIAS_PASSWORD
    artifacts:
      - build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - "your-email@example.com"

  nativescript-ios:
    name: NativeScript iOS Build
    environment:
      vars:
        NODE_VERSION: 18
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Node.js
        script: |
          nvm install $NODE_VERSION
          nvm use $NODE_VERSION
      - name: Install NativeScript CLI
        script: |
          npm install -g nativescript
      - name: Install Dependencies
        script: |
          npm install
      - name: Build iOS
        script: |
          tns build ios --release --provision $PROVISIONING_PROFILE
    artifacts:
      - platforms/ios/build/Release-iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - "your-email@example.com"
